# SeriesOfTubes workflow configuration
# Copy this to .tubes.yaml to customize workflow behavior
# 
# NOTE: This file is for non-sensitive configuration only.
# API keys and secrets should be set in .env file

llm:
  provider: openai  # or anthropic
  model: gpt-4o
  api_key_env: OPENAI_API_KEY  # References env var from .env
  temperature: 0.7
  max_tokens: 4096

http:
  timeout: 30
  retry_attempts: 3
  user_agent: "SeriesOfTubes/1.0"

execution:
  max_duration: 300  # 5 minutes
  save_intermediate: true
  parallel_limit: 5

cache:
  enabled: true
  ttl: 3600  # 1 hour

# All sensitive values (API keys, passwords, secrets) 
# should be set in .env file, not here
