version: '3.8'

services:
  # Frontend (Development with hot reload)
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: seriesoftubes-frontend-dev
    ports:
      - "${FRONTEND_PORT:-3000}:3000"  # Vite configured to run on 3000
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - VITE_API_URL=http://localhost:${API_PORT:-8000}
      - VITE_API_PROXY_URL=http://api-dev:8000
    profiles: ["dev"]  # Only starts with --profile dev
    depends_on:
      - api-dev
    restart: unless-stopped

  # Frontend (Production build)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: seriesoftubes-frontend
    ports:
      - "80:80"
    depends_on:
      - api
    profiles: ["prod"]  # Only starts with --profile prod
    restart: unless-stopped

  # API Server (Production mode - no hot reload)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seriesoftubes-api
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://seriesoftubes:development-password@postgres:5432/seriesoftubes
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-development-secret-key-change-in-production}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://localhost:5173,http://localhost}
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=seriesoftubes
      - MINIO_SECURE=false
      - GREENLET_USE_STANDARD_SWITCHING=yes
    volumes:
      - ./logs:/app/logs
      - ./workflows:/app/workflows:ro
      - ./docs:/app/docs:ro  # Mount docs directory read-only
      - ./.tubes.yaml:/app/.tubes.yaml:ro  # Mount tubes config file
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    profiles: ["with-api"]  # Only starts with --profile with-api

  # API Server (Development mode with hot reload)
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: seriesoftubes-api-dev
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://seriesoftubes:development-password@postgres:5432/seriesoftubes
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-development-secret-key-change-in-production}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://localhost:5173,http://localhost}
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=seriesoftubes
      - MINIO_SECURE=false
      - GREENLET_USE_STANDARD_SWITCHING=yes
    volumes:
      - ./src:/app/src  # Mount only source code for hot reload
      - ./tests:/app/tests  # Mount tests
      - ./workflows:/app/workflows  # Mount example workflows
      - ./logs:/app/logs
      - ./docs:/app/docs  # Mount docs directory
      - ./alembic:/app/alembic  # Mount alembic migrations
      - ./alembic.ini:/app/alembic.ini:ro  # Mount alembic config
      - ./.env:/app/.env:ro  # Mount env file if exists
      - ./.tubes.yaml:/app/.tubes.yaml:ro  # Mount tubes config file
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    profiles: ["dev"]  # Only starts with --profile dev

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: seriesoftubes-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # PostgreSQL for production-like development
  postgres:
    image: postgres:16-alpine
    container_name: seriesoftubes-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: seriesoftubes
      POSTGRES_PASSWORD: development-password
      POSTGRES_DB: seriesoftubes
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seriesoftubes"]
      interval: 5s
      timeout: 3s
      retries: 5

  # MinIO for S3-compatible object storage
  minio:
    image: minio/minio:latest
    container_name: seriesoftubes-minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_DEFAULT_BUCKETS: seriesoftubes
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Celery worker for background job execution
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker  # Use worker dockerfile with non-root user
    container_name: seriesoftubes-worker
    command: celery -A seriesoftubes.tasks worker --loglevel=info --queues=workflows,nodes
    environment:
      - DATABASE_URL=postgresql+asyncpg://seriesoftubes:development-password@postgres:5432/seriesoftubes
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=seriesoftubes
      - MINIO_SECURE=false
      - GREENLET_USE_STANDARD_SWITCHING=yes
    volumes:
      - ./src:/app/src
      - ./workflows:/app/workflows
      - ./outputs:/app/outputs
      - ./logs:/app/logs
      - ./.tubes.yaml:/app/.tubes.yaml:ro  # Mount tubes config file
      - ./.env:/app/.env:ro  # Mount env file if exists
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: unless-stopped
    profiles: ["dev", "with-worker"]  # Only starts with --profile dev or --profile with-worker

volumes:
  redis_data:
  postgres_data:
  api-dev-cache:
  minio_data: