"""Add storage_keys to executions table

Revision ID: a15dbfb85e3e
Revises: 282f82529b59
Create Date: 2025-06-28 21:50:03.745275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15dbfb85e3e'
down_revision: Union[str, None] = '282f82529b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('storage_keys', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'storage_keys')
    # ### end Alembic commands ###
