name: simple-test
version: "1.0.0"
description: A simple test workflow

inputs:
  company_name:
    type: string
    required: true
  include_news:
    type: boolean
    default: false

nodes:
  classify_company:
    type: llm
    depends_on: []
    config:
      prompt: |
        Classify this company: {{ inputs.company_name }}

        Return a JSON object with:
        - industry: string
        - size: "startup" | "smb" | "enterprise"
        - public: boolean
      schema:
        industry: string
        size: string
        public: boolean

  fetch_data:
    type: http
    depends_on: [classify_company]
    config:
      context:
        company: classify_company
      url: "https://api.github.com/search/repositories"
      method: GET
      params:
        q: "{{ inputs.company_name }} language:python"
        sort: "stars"
        order: "desc"
        per_page: 5
      headers:
        Accept: "application/vnd.github.v3+json"

  decide_analysis:
    type: route
    depends_on: [classify_company]
    config:
      context:
        company: classify_company
      routes:
        - when: company.size == "enterprise"
          to: deep_analysis
        - when: company.size == "startup"
          to: quick_analysis
        - default: true
          to: standard_analysis

  deep_analysis:
    type: llm
    depends_on: [fetch_data]
    config:
      context:
        data: fetch_data
        company: classify_company
      prompt: |
        Based on the GitHub search results for {{ inputs.company_name }}, write a brief summary.

        Company classification: {{ company }}

        Top repositories found:
        {{ data.items|length }} repositories total.

        Just provide a 2-3 sentence summary.

  quick_analysis:
    type: llm
    depends_on: [fetch_data]
    config:
      context:
        data: fetch_data
      prompt: |
        Quick summary: Found {{ data.total_count }} repositories for {{ inputs.company_name }} on GitHub.

  standard_analysis:
    type: llm
    depends_on: [fetch_data]
    config:
      context:
        data: fetch_data
        company: classify_company
      prompt: |
        GitHub analysis for {{ inputs.company_name }}:
        - Company type: {{ company.size }}
        - Total repositories found: {{ data.total_count }}

        Provide a brief summary.

outputs:
  classification: classify_company
  analysis: decide_analysis  # Will contain whichever analysis ran
